name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.12.15', '2.13.6', '3.0.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        run: sbt ++${{ matrix.scala }} clean test
      - name: Build and test benchmarks
        if: ${{ matrix.scala == '2.13.6' }}
        run: sbt ++${{ matrix.scala }} benchmarks/test
